// creating the menu
// continua aggiungere dal line 404 (beef devilled)
const menu = {
   sri_lankan: [
      {
         type: "rice",
         name: "mix rice",
         price: ["10.00", "15.00"],
         ingredient: [
            ["pollo", "manzo", "suino", "gamberi"],
            ["riso basmathi", "uova", "carote", "porri", "zenzero"],
         ],
      },
      {
         type: "rice",
         name: "special rice",
         price: ["25:00"],
         ingredient: [[], []],
      },
      {
         type: "rice",
         name: "chicken rice",
         price: ["8.00", "12.00"],
         ingredient: [
            ["pollo"],
            ["riso basmathi", "uova", "carote", "porri", "aglio", "zenzero"],
         ],
      },
      {
         type: "rice",
         name: "egg rice",
         price: ["7.00", "10.00"],
         ingredient: [
            ["pollo"],
            ["riso basmathi", "uova", "carote", "porri", "aglio", "zenzero"],
         ],
      },
      {
         type: "rice",
         name: "prawn rice",
         price: ["15.00"],
         ingredient: [
            ["gamberi"],
            ["riso basmathi", "uova", "carote", "porri", "aglio", "zenzero"],
         ],
      },
      {
         type: "rice",
         name: "nasi goreng",
         price: ["20.00"],
         ingredient: [
            ["pollo", "gamberi"],
            [
               "riso basmathi",
               "peperoni",
               "anacardi",
               "uova",
               "cetriolo",
               "aglio",
               "cipolla",
               "carote",
               "zenzero",
            ],
         ],
      },
      {
         type: "batter",
         name: "prawns batter",
         price: ["20.00"],
         ingredient: [
            ["gamberi"],
            ["farina di mais", "grano tenero", "uova", "sale"],
         ],
      },
      {
         type: "batter",
         name: "cutter fish batter",
         price: ["20.00"],
         ingredient: [
            ["seppie"],
            ["farina di mais", "grano tenero", "uova", "sale"],
         ],
      },
      {
         type: "batter",
         name: "fish batter",
         price: ["20.00"],
         ingredient: [
            ["pesce"],
            ["farina di mais", "grano tenero", "uova", "sale"],
         ],
      },
      {
         type: "noodles",
         name: "mix noodles",
         price: ["10.00", "16.00"],
         ingredient: [
            ["pollo", "manzo", "suino", "gamberi"],
            [
               "spaghetti a pezzetti di riso",
               "carote",
               "porri",
               "uova",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "noodles",
         name: "chicken noodles",
         price: ["10.00", "14.00"],
         ingredient: [
            ["pollo"],
            [
               "spaghetti a pezzetti di riso",
               "carote",
               "porri",
               "uova",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "noodles",
         name: "egg noodles",
         price: ["10.00", "14.00"],
         ingredient: [
            [],
            [
               "spaghetti a pezzetti di riso",
               "carote",
               "porri",
               "uova",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "noodles",
         name: "sea food noodles",
         price: ["12.00", "18.00"],
         ingredient: [
            ["gamberi", "seppia", "pesce"],
            [
               "spaghetti a pezzetti di riso",
               "carote",
               "porri",
               "uova",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "noodles",
         name: "prawn noodles",
         price: ["10.00", "15.00"],
         ingredient: [
            ["gamberi"],
            [
               "spaghetti a pezzetti di riso",
               "carote",
               "porri",
               "uova",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "chili",
         name: "chili chicken",
         price: ["20.00"],
         ingredient: [
            ["pollo"],
            ["salsa piccante", "farina di mais", "carote", "chipolla"],
         ],
      },
      {
         type: "chili",
         name: "chili pork",
         price: ["20.00"],
         ingredient: [
            ["suino"],
            ["salsa piccante", "farina di mais", "carote", "chipolla"],
         ],
      },
      {
         type: "chili",
         name: "chili beef",
         price: ["20.00"],
         ingredient: [
            ["manzo"],
            ["salsa piccante", "farina di mais", "carote", "chipolla"],
         ],
      },
      {
         type: "kottu",
         name: "mix kottu",
         price: ["10.00", "15.00"],
         ingredient: [
            ["pollo", "manzo", "suino"],
            [
               "piadina a pezzetti tipo 00",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "kottu",
         name: "chicken kottu",
         price: ["8.00", "14.00"],
         ingredient: [
            ["pollo"],
            [
               "piadina a pezzetti tipo 00",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "kottu",
         name: "cheese kottu",
         price: ["15.00", "20.00"],
         ingredient: [
            ["pollo", "manzo", "suino"],
            [
               "piadina a pezzetti tipo 00",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "kottu",
         name: "beef kottu",
         price: ["10.00", "15.00"],
         ingredient: [
            ["manzo"],
            [
               "piadina a pezzetti tipo 00",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "kottu",
         name: "pork kottu",
         price: ["10.00", "15.00"],
         ingredient: [
            ["suino"],
            [
               "piadina a pezzetti tipo 00",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "kottu",
         name: "egg kottu",
         price: ["10.00"],
         ingredient: [
            [],
            [
               "piadina a pezzetti tipo 00",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "kottu",
         name: "string hoppers kottu",
         price: ["10.00"],
         ingredient: [
            ["pollo", "manzo", "suino"],
            [
               "spaghetti di riso",
               "porri",
               "carote",
               "uova",
               "salsa di soiya",
               "salsa di ostriche",
               "cappuccio",
               "uova",
               "aglio",
            ],
         ],
      },
      {
         type: "fried",
         name: "mixed fried",
         price: ["20.00"],
         ingredient: [
            ["pollo", "manzo", "suino", "gamberi", "pecse"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "fried",
         name: "beef fried",
         price: ["12.00", "18.00"],
         ingredient: [
            ["manzo"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "fried",
         name: "pork fried",
         price: ["12.00", "18.00"],
         ingredient: [
            ["suino"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "fried",
         name: "chicken fried",
         price: ["10.00", "15.00"],
         ingredient: [
            ["pollo"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "fried",
         name: "fish fried",
         price: ["12.00", "18.00"],
         ingredient: [
            ["pesce"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "fried",
         name: "prawn fried",
         price: ["14.00", "20.00"],
         ingredient: [
            ["gamberi"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "fried",
         name: "cuttlefish fried",
         price: ["14.00", "20.00"],
         ingredient: [
            ["seppia"],
            ["cipolla", "peperoni", "aglio", "zenzero", "pepe", "sale"],
         ],
      },
      {
         type: "devilled",
         name: "chicken devilled",
         price: ["10.00", "15.00"],
         ingredient: [
            ["pollo"],
            ["kechup", "aglio", "zenzero", "cipolla", "pomodoro"],
         ],
      },
      {
         type: "devilled",
         name: "beef devilled",
         price: ["12.00", "18.00"],
         ingredient: [
            ["manzo"],
            ["kechup", "aglio", "zenzero", "cipolla", "pomodoro"],
         ],
      },
      {
         type: "devilled",
         name: "pork devilled",
         price: ["12.00", "16.00"],
         ingredient: [
            ["suino"],
            ["kechup", "aglio", "zenzero", "cipolla", "pomodoro"],
         ],
      },
      {
         type: "devilled",
         name: "fish devilled",
         price: ["12.00", "18.00"],
         ingredient: [
            ["pesce"],
            ["kechup", "aglio", "zenzero", "cipolla", "pomodoro"],
         ],
      },
      {
         type: "devilled",
         name: "prawn devilled",
         price: ["14.00", "20.00"],
         ingredient: [
            ["gamberi"],
            ["kechup", "aglio", "zenzero", "cipolla", "pomodoro"],
         ],
      },
      {
         type: "devilled",
         name: "cuttlefish devilled",
         price: ["14.00", "20.00"],
         ingredient: [
            ["seppie"],
            ["kechup", "aglio", "zenzero", "cipolla", "pomodoro"],
         ],
      },
      {
         type: "stew",
         name: "chicken stew",
         price: ["16.00"],
         ingredient: [["pollo"], ["chipolla", "aglio", "zenzero", "pepe nero"]],
      },
      {
         type: "stew",
         name: "beef stew",
         price: ["18.00"],
         ingredient: [["manzo"], ["chipolla", "aglio", "zenzero", "pepe nero"]],
      },
      {
         type: "stew",
         name: "pork stew",
         price: ["18.00"],
         ingredient: [["suino"], ["chipolla", "aglio", "zenzero", "pepe nero"]],
      },
      {
         type: "short eats",
         name: "beef roti",
         price: ["2.00"],
         ingredient: [
            ["manzo"],
            [
               "farina tipo 00",
               "patate",
               "porri",
               "sale",
               "pepe",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "short eats",
         name: "vegetable roti",
         price: ["2.00"],
         ingredient: [
            [],
            [
               "farina tipo 00",
               "patate",
               "porri",
               "sale",
               "pepe",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "short eats",
         name: "rolls",
         price: ["1.50"],
         ingredient: [
            ["tonno"],
            ["cipolla", "patate", "sale", "pepe", "aglio", "zenzero"],
         ],
      },
      {
         type: "short eats",
         name: "cutlet",
         price: ["1.00"],
         ingredient: [
            ["tonno"],
            ["cipolla", "patate", "sale", "pepe", "aglio", "zenzero"],
         ],
      },
      {
         type: "short eats",
         name: "fish bun",
         price: ["2.00"],
         ingredient: [
            ["pesce"],
            [
               "farina tipo 00",
               "cipolla",
               "patate",
               "porri",
               "aglio",
               "zenzero",
            ],
         ],
      },
      {
         type: "short eats",
         name: "patties",
         price: ["2.00"],
         ingredient: [
            ["tonno"],
            [
               "farina tipo 00",
               "cipolla",
               "patate",
               "aglio",
               "zenzero",
               "pepe",
               "sale",
            ],
         ],
      },
   ],
   pizza: [
      {
         type: "classiche",
         name: "marina",
         price: "4.00",
         ingredient: ["pomodoro", "origano", "aglio", "basilico", "olio evo"],
      },
      {
         type: "classiche",
         name: "cosacca",
         price: "4.50",
         ingredient: ["pomodoro", "grana", "basilico", "olio evo"],
      },
      {
         type: "classiche",
         name: "margherita",
         price: "5.00",
         ingredient: ["pomodoro", "fior di latte", "basilico", "olio evo"],
      },
      {
         type: "classiche",
         name: "diavola",
         price: "6.50",
         ingredient: ["pomodoro", "fior di latte", "salame piccante"],
      },
      {
         type: "classiche",
         name: "siciliana",
         price: "6.50",
         ingredient: [
            "pomodoro",
            "fior di latte",
            "melanzane",
            "basilico",
            "oli evo",
         ],
      },
      {
         type: "classiche",
         name: "napoletana",
         price: "8.00",
         ingredient: [
            "pomodoro",
            "mozzarella di bufala",
            "basilico",
            "scaglie di grana",
            "olio evo",
         ],
      },
      {
         type: "classiche",
         name: "ortolana",
         price: "7.50",
         ingredient: [
            "pomodoro",
            "fior di latte",
            "peperoni",
            "melanzane",
            "funghi",
            "zucchine",
            "friarielli",
         ],
      },

      {
         type: "classiche",
         name: "capricciosa",
         price: "7.50",
         ingredient: [
            "pomodoro",
            "funghi",
            "prosciutto",
            "salame",
            "olive",
            "carciofini",
            "fior di latte",
            "basilico",
            "olio evo",
         ],
      },
      {
         type: "classiche",
         name: "prosciutto e funghi",
         price: "6.50",
         ingredient: ["pomodoro", "fior di latte", "prosciutto e funghi"],
      },
      {
         type: "classiche",
         name: "tonno e cipolla",
         price: "7.00",
         ingredient: [
            "pomodoro",
            "tonno",
            "pomodorini",
            "cipolla",
            "basilico",
            "olio evo",
            "scorza di limone",
         ],
      },
      {
         type: "classiche",
         name: "estate",
         price: "7.00",
         ingredient: ["pomodoro", "crudo", "burrata", "basilico", "olio evo"],
      },
      {
         type: "pizze bianche",
         name: "mimosa",
         price: "6.00",
         ingredient: [
            "fior di latte",
            "panna",
            "prosciutto cotto",
            "mais",
            "basilico",
         ],
      },
      {
         type: "pizze bianche",
         name: "primavera",
         price: "6.50",
         ingredient: ["fior di latte", "pomodorini", "basilico", "olio evo"],
      },
      {
         type: "pizze bianche",
         name: "4 formaggi",
         price: "8.00",
         ingredient: [
            "gorgonzola",
            "fior di latte",
            "fontina",
            "emmental",
            "basilico",
         ],
      },
      {
         type: "pizze bianche",
         name: "inverno",
         price: "7.00",
         ingredient: ["fior di latte", "salsiccia", "friarielli"],
      },
      {
         type: "pizze bianche",
         name: "viennese",
         price: "6.50",
         ingredient: ["fior di latte", "wurstel", "patatine"],
      },
      {
         type: "pizze bianche",
         name: "bufalina",
         price: "8.00",
         ingredient: [
            "pomodorini",
            "mozzarella di bufala",
            "basilico",
            "olio evo",
         ],
      },
      {
         type: "pizze bianche",
         name: "nerano",
         price: "7.00",
         ingredient: [
            "fior di latte",
            "zucchine",
            "grana",
            "basilico",
            "olio evo",
         ],
      },
      {
         type: "pizze bianche",
         name: "pistacchiosa",
         price: "8.00",
         ingredient: [
            "fior di latte",
            "pesto di pistacchio",
            "mortadella",
            "granella di pistacchio",
            "stracciatella di burrata",
            "basilico",
         ],
      },
      {
         type: "pizze bianche",
         name: "ripieno",
         price: "7.00",
         ingredient: [
            "pomodoro",
            "ricotta",
            "salame",
            "fior di latte",
            "olio evo",
            "basilico",
         ],
      },
      {
         type: "pizze bianche",
         name: "4 stagioni",
         price: "6.50",
         ingredient: ["pomodoro", "mozzarella", "prosciutto", "salamino"],
      },
      {
         type: "pizze bianche",
         name: "bresaola",
         price: "8.00",
         ingredient: ["pomodoro", "mozzarella", "bresaola", "rucola", "grana"],
      },
      {
         type: "pizze bianche",
         name: "wurstel",
         price: "6.00",
         ingredient: ["pomodoro", "mozzarella", "wurstel"],
      },
   ],
   bibite: [
      {
         type: "birre alla spina",
         name: "Heineken",
         size: "piccolo",
         volume: "0.2 CL",
         price: ["3.00"],
      },
      {
         type: "birre alla spina",
         name: "Heineken",
         size: "medio",
         volume: "0.4 CL",
         price: ["4.00"],
      },
      {
         type: "birre alla spina",
         name: "messina non filtrata",
         size: "piccolo",
         volume: "0.2 CL",
         price: ["3.50"],
      },
      {
         type: "birre alla spina",
         name: "messina non filtrata",
         size: "medio",
         volume: "0.4 CL",
         price: ["5.00"],
      },
      {
         type: "vino rosso e bianco frizzante alla spina",
         name: "",
         size: "",
         volume: "1/4 LITRI",
         price: ["4.00"],
      },
      {
         type: "vino rosso e bianco frizzante alla spina",
         name: "",
         size: "",
         volume: "1/2 LITRI",
         price: ["6.00"],
      },
      {
         type: "vino rosso e bianco frizzante alla spina",
         name: "",
         size: "",
         volume: "1 LITRI",
         price: ["10.00"],
      },
      {
         type: "birre",
         name: "corona",
         size: "",
         volume: "33 CL",
         price: ["4.00"],
      },
      {
         type: "birre",
         name: "bud",
         size: "",
         volume: "33 CL",
         price: ["4.00"],
      },
      {
         type: "birre",
         name: "ichnusa non filtrato",
         size: "",
         volume: "50 CL",
         price: ["4.50"],
      },
      {
         type: "birre",
         name: "moretti",
         size: "",
         volume: "66 CL",
         price: ["4.50"],
      },
      {
         type: "birre",
         name: "kapuziner hefe weizen",
         size: "",
         volume: "50 CL",
         price: ["5.00"],
      },
      {
         type: "vini",
         name: "soligo prosec",
         size: "",
         volume: "75 CL",
         price: ["13.00"],
      },
      {
         type: "vini",
         name: "adami bardolino doc",
         size: "",
         volume: "75 CL",
         price: ["13.00"],
      },
      {
         type: "vini",
         name: "custoza doc",
         size: "",
         volume: "75 CL",
         price: ["13.00"],
      },
      {
         type: "vini",
         name: "recchia vale doc classico",
         size: "",
         volume: "75 CL",
         price: ["13.00"],
      },
      {
         type: "bibite",
         name: "acqua naturale",
         size: "",
         volume: "75 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "acqua frizzante",
         size: "",
         volume: "75 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "coca cola",
         size: "",
         volume: "33 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "coca cola 0",
         size: "",
         volume: "33 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "red bull",
         size: "",
         volume: "25 CL",
         price: ["3.50"],
      },
      {
         type: "bibite",
         name: "sprite",
         size: "",
         volume: "33 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "tè pesca",
         size: "",
         volume: "33 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "tè limone",
         size: "",
         volume: "33 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "tè pesca",
         size: "",
         volume: "50 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "tè limone",
         size: "",
         volume: "50 CL",
         price: ["2.50"],
      },
      {
         type: "bibite",
         name: "coca cola",
         size: "",
         volume: "100 CL",
         price: ["3.50"],
      },
      {
         type: "bibite",
         name: "coca cola 0",
         size: "",
         volume: "100 CL",
         price: ["3.50"],
      },
      {
         type: "bibite",
         name: "pepsi",
         size: "",
         volume: "100 CL",
         price: ["3.50"],
      },
      {
         type: "bibite",
         name: "pepsi twist",
         size: "",
         volume: "100 CL",
         price: ["3.50"],
      },
   ],
   dessert: [
      {
         type: "dessert",
         name: "watalappan",
         price: ["2.50"],
         ingredient: [[], ["uova", "zucchero", "latte"]],
      },
   ],
   iceCream: [
      {
         type: "ice cream",
         name: "gelato",
         price: ["3.00"],
         ingredient: [[], []],
      },
   ],
   frutta: [
      {
         type: "frutta",
         name: "frutta mist",
         price: [],
         ingredient: [[], []],
      },
   ],
};

// exporting menu as a JSON
const menu_data = JSON.stringify(menu);

export { menu_data };
